### ISSUE TITLE
Feature request - Email timeout

### ISSUE THREAD

**Issue by dirkwa** [amirlanesman/signalk-to-nfl#2]
Currently the timeout is set to 1000 in 0.0.5. To support low performance CPUs like Vitron Energy Octo GX or Venus GX a value of 3000 would be nice.

**Comment by amirlanesman** [comment]
made this into a parameter so each user can set to appropriate value.

[e625ea08af01e3d1ba41285fadbabc002f8f9d66](https://github.com/amirlanesman/signalk-to-nfl/commit/e625ea08af01e3d1ba41285fadbabc002f8f9d66)
