### ISSUE TITLE
Feature request - More precise position when on the hard or dock

### ISSUE THREAD

**Issue by dirkwa** [amirlanesman/signalk-to-nfl#3]
I use 200m insted of 50m because my swing radius at anchor is easy 100 - 150m in the area I am currently. Beeing at anchor or underway this value works great. Before I have been contacted by Steve Neil that I am sending too much data points and this will on the long run mess up my "show journey". This was before he announced his new optimized track algorithm, so I am unsure if this is still the case or if he already filters server side. Anyhow, I noticed it also when moving inside a marina from dock A to B or I pull into a marina and tie to a dock that my position is not shown correctly because I have not moved outside my radius. My idea would be that if SOG = 0 and the last 10 data points are within 1m and the last reported is more away than 10m than report the position.

Maybe this values have to be tuned a little more but could be a good start.

Thanks for your effort!

**Comment by amirlanesman** [comment]
as a simple solution I added a new parameter `minSpeed` which means a position will only be recorded if an SOG of more than `minSpeed` has been logged between the previous position and the current one.

while on anchor/mooring/dock I expect that SOG will be low and it should minimize positions on anchor.

more advice always welcome!

[0917202daff6c4b2aee1fbc69eead7b93009377f](https://github.com/amirlanesman/signalk-to-nfl/commit/0917202daff6c4b2aee1fbc69eead7b93009377f)
