### ISSUE TITLE
0N and 0E as positions in track N2k bus shutdown.

### ISSUE THREAD

**Issue by dirkwa** [amirlanesman/signalk-to-nfl#9]
First of all I love this plugin and it has been flawless for me. Thank you soo much for your effort!

Friends have a issue - I know they use the plugin 0.1.5 on a CE Cebro and it's connected to the N2k network for the GPS position. Data source is default. They shut down their NAV-BUS (n2k) when at anchor. I saw in their journey that 0N and 0E is transmitted from time to time. I thought this was filtered my the plugin already. To fix it they delete manually the position on the NFL website.
Here the boat details:

https://www.noforeignland.com/boat/5641065937764352

**Comment by bergie** [comment]
This seems to happen with Signal K also with other CAN setups than just Cerbo. We also occasionally get 0,0 written to NFL at a N2K reboot.

**Comment by dirkwa** [comment]
At this boat is a marker in the center of antarctica.

https://www.noforeignland.com/boat/6141223033110528

**Comment by tkurki** [comment]
Any idea what the actual input it that is converted to 0,0 instead of `null` like it should?

**Comment by tkurki** [comment]
…as this should be fixed as far upstream as reasonable, probably in n2k-signalk.

**Comment by bergie** [comment]
Sadly no N2K log for it, but I saw actual 0,0 as values in Signal K data browser, as coming from the GPS on the Orca Core.
